---
name: Filiicodex
version: 6.0.2
slug: filiicodex
description: A Filiicodex add-on for Home Assistant
url: https://github.com/filii-lamberti/addon-filiicodex
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
homeassistant_api: true
ports:
  3000/tcp: 8051 # C+O+D+E+X
options:
schema:
  purge: bool?
  logging: bool?
  debugging: bool?
image: ghcr.io/filii-lamberti/filiicodex/{arch}