name: Continuous integration

on:
  workflow_call:
    inputs:
      addon:
        required: true
        type: string

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: ./${{ inputs.addon }}/rootfs/opt/${{ inputs.addon }}/package-lock.json
      - name: Install ESLint and dependencies
        run: npm install
        working-directory: ./${{ inputs.addon }}/rootfs/opt/${{ inputs.addon }}
      - name: Run ESLint
        run: node_modules/eslint/bin/eslint.js index.js
        working-directory: ./${{ inputs.addon }}/rootfs/opt/${{ inputs.addon }}

  test:
    needs: lint
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set add-on version
        run: |
          sed -i "s/dev/latest/g" ${{ inputs.addon }}/config.yaml
      - name: Build and push latest Docker image
        uses: home-assistant/builder@2023.03.0
        with:
          args: |
            --amd64 \
            --target ${{ inputs.addon }} \
            --image "${{ inputs.addon }}/{arch}" \
            --docker-hub "ghcr.io/filii-lamberti"

  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
