name: Continuous integration

on:
  workflow_call:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: ./filiibot/rootfs/opt/filiibot/package-lock.json
      - name: Install ESLint and dependencies
        run: npm install
        working-directory: ./filiibot/rootfs/opt/filiibot
      - name: Run ESLint
        run: node_modules/eslint/bin/eslint.js bot.js base/* commands/* events/*
        working-directory: ./filiibot/rootfs/opt/filiibot

  test:
    needs: lint
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set add-on version
        run: |
          sed -i "s/dev/latest/g" filiibot/config.json
      - name: Build and push latest Docker image
        uses: home-assistant/builder@2021.09.0
        with:
          args: |
            --amd64 \
            --target filiibot \
            --image "filiibot/{arch}" \
            --docker-hub "ghcr.io/filii-lamberti"

  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
